tap "heroku/brew"
tap "stripe/stripe-cli"
tap "withgraphite/tap"

# Core CLI tools
brew "asdf"
brew "ca-certificates"
brew "coreutils"
brew "curl"
brew "direnv"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "imagemagick"
brew "libyaml"
brew "neovim"
brew "ripgrep"
brew "pure"
brew "tmux"
brew "withgraphite/tap/graphite"

# Work tools
brew "detect-secrets"
brew "graphviz"
brew "lefthook"
brew "libpq"
brew "overmind"
brew "pipx"
brew "pnpm"
brew "postgresql@17"
brew "python-setuptools"
brew "python@3.10"
brew "semgrep"
brew "heroku/brew/heroku"
brew "stripe/stripe-cli/stripe"

# Apps
cask "ghostty"
